#!/bin/sh

is_lib=0
prepare=0

for arg in "$@"; do
    [ "$prepare" -eq 1 ] && echo "$arg" | grep "\.so" >/dev/null 2>&1 && is_lib=1
    prepare=0
    [ "$arg" = "-o" ] && prepare=1
done

if [ "$is_lib" -eq 1 ]; then
    exec ld  $@ -nostdlib -shared
fi

exec ld ${LDCRT} $@ -nostdlib -shared

